In [1]:
import numpy as np


In [2]:
# create array using numpy  

ar1=np.array([1,2,3,4,5])
print(ar1)

[1 2 3 4 5]


In [3]:
type(ar1)

numpy.ndarray

In [4]:
ar1.shape

(5,)

In [6]:
ar2=np.array([1,2,3,4,5])
ar2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
ar2=np.array([[1,2,3,4,5]])

In [8]:
ar2.shape

(1, 5)

In [11]:
arr2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [14]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# vectorize operation

arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,20,30,40,50,60])

print("addition: ",arr1+arr2)
print("Subtraction: ",arr1-arr2)
print("Multiplecation: ",arr1*arr2)

addition:  [11 22 33 44 55 66]
Subtraction:  [ -9 -18 -27 -36 -45 -54]
Multiplecation:  [ 10  40  90 160 250 360]


In [ ]:
arr=np.array([1,2,3,4,5])

print(np.sqrt(arr))



[1.         1.41421356 1.73205081 2.         2.23606798]


In [22]:
# array slicing and indexing


arr=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr[0][0]

1

In [24]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])